'''

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

'''
def fibonacci(a):
    
    mynums = list(range(1,(a),1))
    fibnums= [1,2]
    sumevens=0
    
    
    for n in mynums:
        if fibnums[n] <= 4000000:  
            fibnums.append( fibnums[n] + fibnums[n-1])
            print(fibnums)

            if (fibnums[n]) %2 == 0:
                sumevens += (fibnums[n])
                print(fibnums[n])
                
        else:
            print('exceeds limit')
            break
        
    print(sumevens)

fibonacci(60)
